/**
 * App-owned official Catalog trust root.
 *
 * These pins are compile-time input. Host/Desktop must inject this object
 * and must never learn a source, key, or repository from dataDir, a
 * downloaded Catalog, or trust-on-first-use.
 */

export const OFFICIAL_CATALOG_SOURCE_ID = 'gian-official' as const;
export const OFFICIAL_CATALOG_REPOSITORY = 'RichLogic/Gian-Proxy-Catalog' as const;
export const OFFICIAL_CATALOG_ARTIFACT_REPOSITORIES = ['RichLogic/Gian'] as const;
export const OFFICIAL_CATALOG_KEY_ID = 'gian-official-catalog-2026' as const;

/** Pinned Ed25519 public key (32-byte raw hex). The matching private key
 * is not in this repository and is never generated by production runtime. */
export const OFFICIAL_CATALOG_PUBLIC_KEY_HEX =
  'b29123f440749e6add2f6706b0d231cfa7136f574724af07c970aec4bea37a51';

export interface OfficialCatalogSourcePolicy {
  sourceId: typeof OFFICIAL_CATALOG_SOURCE_ID | string;
  repository: typeof OFFICIAL_CATALOG_REPOSITORY | string;
  artifactRepositories: readonly string[];
  pinnedPublicKeys: Readonly<Record<string, string>>;
}

export function officialCatalogSourcePolicy(): OfficialCatalogSourcePolicy {
  return {
    sourceId: OFFICIAL_CATALOG_SOURCE_ID,
    repository: OFFICIAL_CATALOG_REPOSITORY,
    artifactRepositories: OFFICIAL_CATALOG_ARTIFACT_REPOSITORIES,
    pinnedPublicKeys: {
      [OFFICIAL_CATALOG_KEY_ID]: OFFICIAL_CATALOG_PUBLIC_KEY_HEX,
    },
  };
}

export function resolvePinnedCatalogPublicKey(
  policy: OfficialCatalogSourcePolicy,
  keyId: string,
): string {
  const key = policy.pinnedPublicKeys[keyId];
  if (typeof key !== 'string' || key.length === 0) {
    throw new Error(`unknown Catalog keyId: ${keyId}`);
  }
  return key;
}
